"""initial schema

Revision ID: 49779e0ff1cb
Revises: 
Create Date: 2026-08-25 09:55:34.625014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49779e0ff1cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('school_name', sa.String(length=160), nullable=False),
    sa.Column('county', sa.String(length=80), nullable=False),
    sa.Column('guardian_name', sa.String(length=120), nullable=False),
    sa.Column('guardian_phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('organisation', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('donated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_sponsor_id'), ['sponsor_id'], unique=False)

    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('awarded_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarships_beneficiary_id'), ['beneficiary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarships_sponsor_id'), ['sponsor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarships_sponsor_id'))
        batch_op.drop_index(batch_op.f('ix_scholarships_beneficiary_id'))

    op.drop_table('scholarships')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_sponsor_id'))

    op.drop_table('donations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_email'))

    op.drop_table('sponsors')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
